import type { Dispatch, SetStateAction } from "react";
import type { ClipboardEntry, Locale } from "../../shared/types";
import type { AiProfile, AppCleanupPolicy } from "../settings/types";

export type StateSetter<T> = Dispatch<SetStateAction<T>>;

export type InstalledAppOption = { label: string; value: string };
export type DefaultAppsMap = Record<string, string>;
export type QuickPasteModifier = "disabled" | "ctrl" | "alt" | "shift" | "win";
export type SettingsSubpage = "home" | "advanced" | "theme-store";

export type CloudSyncContentPrefs = {
  text: boolean;
  image: boolean;
  file_path: boolean;
  emoji: boolean;
};

export const DEFAULT_CLOUD_SYNC_CONTENT_PREFS: CloudSyncContentPrefs = {
  text: true,
  image: true,
  file_path: true,
  emoji: true
};

export interface AppState {
  showSettings: boolean;
  setShowSettings: StateSetter<boolean>;
  settingsSubpage: SettingsSubpage;
  setSettingsSubpage: StateSetter<SettingsSubpage>;
  showTagManager: boolean;
  setShowTagManager: StateSetter<boolean>;
  tagManagerEnabled: boolean;
  setTagManagerEnabled: StateSetter<boolean>;
  collapsedGroups: Record<string, boolean>;
  setCollapsedGroups: StateSetter<Record<string, boolean>>;
  history: ClipboardEntry[];
  setHistory: StateSetter<ClipboardEntry[]>;
  search: string;
  setSearch: StateSetter<string>;
  isComposing: boolean;
  setIsComposing: StateSetter<boolean>;
  searchIsFocused: boolean;
  setSearchIsFocused: StateSetter<boolean>;
  showTagFilter: boolean;
  setShowTagFilter: StateSetter<boolean>;
  tagInput: string;
  setTagInput: StateSetter<string>;
  showEmojiPanel: boolean;
  setShowEmojiPanel: StateSetter<boolean>;
  emojiFavorites: string[];
  setEmojiFavorites: StateSetter<string[]>;
  aiOptionsOpenId: number | null;
  setAiOptionsOpenId: StateSetter<number | null>;
  editingTagsId: number | null;
  setEditingTagsId: StateSetter<number | null>;
  revealedIds: Set<number>;
  setRevealedIds: StateSetter<Set<number>>;
  autoStart: boolean;
  setAutoStart: StateSetter<boolean>;
  deduplicate: boolean;
  setDeduplicate: StateSetter<boolean>;
  persistent: boolean;
  setPersistent: StateSetter<boolean>;
  persistentLimitEnabled: boolean;
  setPersistentLimitEnabled: StateSetter<boolean>;
  persistentLimit: number;
  setPersistentLimit: StateSetter<number>;
  appSettings: Record<string, string>;
  setAppSettings: StateSetter<Record<string, string>>;
  defaultApps: DefaultAppsMap;
  setDefaultApps: StateSetter<DefaultAppsMap>;
  showAppSelector: string | null;
  setShowAppSelector: StateSetter<string | null>;
  chatMode: boolean;
  setChatMode: StateSetter<boolean>;
  installedApps: InstalledAppOption[];
  setInstalledApps: StateSetter<InstalledAppOption[]>;
  dataPath: string;
  setDataPath: StateSetter<string>;
  hotkey: string;
  setHotkey: StateSetter<string>;
  sequentialHotkey: string;
  setSequentialHotkey: StateSetter<string>;
  richPasteHotkey: string;
  setRichPasteHotkey: StateSetter<string>;
  searchHotkey: string;
  setSearchHotkey: StateSetter<string>;
  screenshotHotkey: string;
  setScreenshotHotkey: StateSetter<string>;
  quickPasteModifier: QuickPasteModifier;
  setQuickPasteModifier: StateSetter<QuickPasteModifier>;
  sequentialMode: boolean;
  setSequentialModeState: StateSetter<boolean>;
  isRecording: boolean;
  setIsRecording: StateSetter<boolean>;
  isRecordingSequential: boolean;
  setIsRecordingSequential: StateSetter<boolean>;
  isRecordingRich: boolean;
  setIsRecordingRich: StateSetter<boolean>;
  isRecordingSearch: boolean;
  setIsRecordingSearch: StateSetter<boolean>;
  isRecordingScreenshot: boolean;
  setIsRecordingScreenshot: StateSetter<boolean>;
  deleteAfterPaste: boolean;
  setDeleteAfterPaste: StateSetter<boolean>;
  moveToTopAfterPaste: boolean;
  setMoveToTopAfterPaste: StateSetter<boolean>;
  privacyProtection: boolean;
  setPrivacyProtection: StateSetter<boolean>;
  privacyProtectionKinds: string[];
  setPrivacyProtectionKinds: StateSetter<string[]>;
  privacyProtectionCustomRules: string;
  setPrivacyProtectionCustomRules: StateSetter<string>;
  sensitiveMaskPrefixVisible: number;
  setSensitiveMaskPrefixVisible: StateSetter<number>;
  sensitiveMaskSuffixVisible: number;
  setSensitiveMaskSuffixVisible: StateSetter<number>;
  sensitiveMaskEmailDomain: boolean;
  setSensitiveMaskEmailDomain: StateSetter<boolean>;
  cleanupRules: string;
  setCleanupRules: StateSetter<string>;
  appCleanupPolicies: AppCleanupPolicy[];
  setAppCleanupPolicies: StateSetter<AppCleanupPolicy[]>;
  captureFiles: boolean;
  setCaptureFiles: StateSetter<boolean>;
  captureRichText: boolean;
  setCaptureRichText: StateSetter<boolean>;
  richTextSnapshotPreview: boolean;
  setRichTextSnapshotPreview: StateSetter<boolean>;
  silentStart: boolean;
  setSilentStart: StateSetter<boolean>;
  followMouse: boolean;
  setFollowMouse: StateSetter<boolean>;
  showAppBorder: boolean;
  setShowAppBorder: StateSetter<boolean>;
  winClipboardDisabled: boolean;
  setWinClipboardDisabled: StateSetter<boolean>;
  registryWinVEnabled: boolean;
  setRegistryWinVEnabled: StateSetter<boolean>;
  pasteMethod: string;
  setPasteMethod: StateSetter<string>;
  theme: string;
  setTheme: StateSetter<string>;
  colorMode: string;
  setColorMode: StateSetter<string>;
  showSourceAppIcon: boolean;
  setShowSourceAppIcon: StateSetter<boolean>;

  compactMode: boolean;
  setCompactMode: StateSetter<boolean>;
  simplifiedMode: boolean;
  setSimplifiedMode: StateSetter<boolean>;
  clipboardItemFontSize: number;
  setClipboardItemFontSize: StateSetter<number>;
  clipboardTagFontSize: number;
  setClipboardTagFontSize: StateSetter<number>;
  emojiPanelEnabled: boolean;
  setEmojiPanelEnabled: StateSetter<boolean>;
  emojiPanelTab: "emoji" | "favorites";
  setEmojiPanelTab: StateSetter<"emoji" | "favorites">;
  showHotkeyHint: boolean;
  setShowHotkeyHint: StateSetter<boolean>;
  showAutoCloseHint: boolean;
  setShowAutoCloseHint: StateSetter<boolean>;
  language: Locale;
  setLanguage: StateSetter<Locale>;
  settingsLoaded: boolean;
  setSettingsLoaded: StateSetter<boolean>;
  isWindowPinned: boolean;
  setIsWindowPinned: StateSetter<boolean>;
  showSearchBox: boolean;
  setShowSearchBox: StateSetter<boolean>;
  scrollTopButtonEnabled: boolean;
  setScrollTopButtonEnabled: StateSetter<boolean>;
  arrowKeySelection: boolean;
  setArrowKeySelection: StateSetter<boolean>;
  hideTrayIcon: boolean;
  setHideTrayIcon: StateSetter<boolean>;
  hideDockIcon: boolean;
  setHideDockIcon: StateSetter<boolean>;
  edgeDocking: boolean;
  setEdgeDocking: StateSetter<boolean>;
  customBackground: string;
  setCustomBackground: StateSetter<string>;
  customBackgroundOpacity: number;
  setCustomBackgroundOpacity: StateSetter<number>;
  surfaceOpacity: number;
  setSurfaceOpacity: StateSetter<number>;
  selectedIndex: number;
  setSelectedIndex: StateSetter<number>;
  isKeyboardMode: boolean;
  setIsKeyboardMode: StateSetter<boolean>;
  isLoadingMore: boolean;
  setIsLoadingMore: StateSetter<boolean>;
  hasMore: boolean;
  setHasMore: StateSetter<boolean>;
  currentOffset: number;
  setCurrentOffset: StateSetter<number>;
  mqttEnabled: boolean;
  setMqttEnabled: StateSetter<boolean>;
  mqttServer: string;
  setMqttServer: StateSetter<string>;
  mqttPort: string;
  setMqttPort: StateSetter<string>;
  mqttUser: string;
  setMqttUser: StateSetter<string>;
  mqttPass: string;
  setMqttPass: StateSetter<string>;
  mqttTopic: string;
  setMqttTopic: StateSetter<string>;
  mqttProtocol: string;
  setMqttProtocol: StateSetter<string>;
  mqttWsPath: string;
  setMqttWsPath: StateSetter<string>;
  mqttNotificationEnabled: boolean;
  setMqttNotificationEnabled: StateSetter<boolean>;
  cloudSyncEnabled: boolean;
  setCloudSyncEnabled: StateSetter<boolean>;
  cloudSyncAuto: boolean;
  setCloudSyncAuto: StateSetter<boolean>;
  cloudSyncProvider: "http" | "webdav";
  setCloudSyncProvider: StateSetter<"http" | "webdav">;
  cloudSyncServer: string;
  setCloudSyncServer: StateSetter<string>;
  cloudSyncApiKey: string;
  setCloudSyncApiKey: StateSetter<string>;
  cloudSyncIntervalSec: string;
  setCloudSyncIntervalSec: StateSetter<string>;
  cloudSyncSnapshotIntervalMin: string;
  setCloudSyncSnapshotIntervalMin: StateSetter<string>;
  cloudSyncWebdavUrl: string;
  setCloudSyncWebdavUrl: StateSetter<string>;
  cloudSyncWebdavUsername: string;
  setCloudSyncWebdavUsername: StateSetter<string>;
  cloudSyncWebdavPassword: string;
  setCloudSyncWebdavPassword: StateSetter<string>;
  cloudSyncWebdavBasePath: string;
  setCloudSyncWebdavBasePath: StateSetter<string>;
  cloudSyncContentPrefs: CloudSyncContentPrefs;
  setCloudSyncContentPrefs: StateSetter<CloudSyncContentPrefs>;
  fileServerEnabled: boolean;
  setFileServerEnabled: StateSetter<boolean>;
  fileServerPort: string;
  setFileServerPort: StateSetter<string>;
  localIp: string;
  setLocalIp: StateSetter<string>;
  availableIps: string[];
  setAvailableIps: StateSetter<string[]>;
  actualPort: string;
  setActualPort: StateSetter<string>;
  fileTransferPath: string;
  setFileTransferPath: StateSetter<string>;
  fileTransferAutoOpen: boolean;
  setFileTransferAutoOpen: StateSetter<boolean>;
  fileTransferAutoCopy: boolean;
  setFileTransferAutoCopy: StateSetter<boolean>;
  fileServerAutoClose: boolean;
  setFileServerAutoClose: StateSetter<boolean>;
  soundEnabled: boolean;
  setSoundEnabled: StateSetter<boolean>;
  pasteSoundEnabled: boolean;
  setPasteSoundEnabled: StateSetter<boolean>;
  soundVolume: number;
  setSoundVolume: StateSetter<number>;
  aiEnabled: boolean;
  setAiEnabled: StateSetter<boolean>;
  aiTargetLang: string;
  setAiTargetLang: StateSetter<string>;
  aiThinkingBudget: string;
  setAiThinkingBudget: StateSetter<string>;
  aiProfiles: AiProfile[];
  setAiProfiles: StateSetter<AiProfile[]>;
  aiAssignedProfileTask: string;
  setAiAssignedProfileTask: StateSetter<string>;
  aiAssignedProfileMouthpiece: string;
  setAiAssignedProfileMouthpiece: StateSetter<string>;
  aiAssignedProfileTranslate: string;
  setAiAssignedProfileTranslate: StateSetter<string>;
  processingAiId: number | null;
  setProcessingAiId: StateSetter<number | null>;
  typeFilter: string | null;
  setTypeFilter: StateSetter<string | null>;
}
